--- # Configure nginx service for key submission
- name: install Ruby Packages + git
  apt: name={{ item }} state=present update_cache=yes
  with_items:
  - rails
  - ruby-sqlite3
  - git
  - ruby-rack
  - ruby-concurrent
  - puma

- name: "Deploy from https://github.com/yanosz/wireguard-rest.git"
  become: true
  become_user: wireguard-rest
  become_method: sudo
  git:
    repo: https://github.com/yanosz/wireguard-rest.git
    dest: /usr/local/wireguard-rest/lib
    clone: yes
    update: yes
    force: yes
  notify:
  - update wireguard_configuration
  - update webapp_db
  - restart wireguard-rest

- name: "Configure /usr/local/wireguard-rest/lib/conf/rest.conf.erb"
  template:
    src: files/rest.conf.erb.j2
    dest: /usr/local/wireguard-rest/lib/config/rest.conf.erb
    owner: wireguard-rest
    group: wireguard-rest
    mode: '0644'
  notify:
  - update wireguard_configuration
  - reload wireguard-rest

- command: 'rake -f /usr/local/wireguard-rest/lib/Rakefile secret'
  register: wireguard_rest_app_secret

- name: "Register systemd socket"
  copy:
    src: files/wireguard-rest.socket
    dest: /etc/systemd/system/wireguard-rest.socket
    owner: root
    group: root
  notify:
  - update wireguard_configuration
  - reload wireguard-rest

- name: "Register systemd service"
  template:
    src: files/wireguard-rest.service.j2
    dest:  /etc/systemd/system/wireguard-rest.service
    owner: root
    group: root
    mode: 0600
  notify:
  - update wireguard_configuration
  - reload wireguard-rest


- name: "Configure: app.yml"
  template:
    src: files/app.yml.j2
    dest: /usr/local/wireguard-rest/lib/config/app.yml
    owner: root
    group: root
    mode: '0644'
  notify:
  - update wireguard_configuration
  - reload wireguard-rest
